### ISSUE TITLE
Add Astro + Deno + Preact

### ISSUE THREAD

**Issue by iainsimmons** [jherr/bun-vs-node-2#1]
Astro + Deno + Preact would be a great comparison to Fresh.

Bonus points for Astro + Deno + Solid, since Solid claims to have some of the fastest SSR speeds around.

Only thing I'm not sure about is if you should be doing the Astro ones with an actual island.

**Comment by jherr** [comment]
I don't think the Island thing matters because oha is only grabbing the HTML page and not doing the subsequent requests or client side work. But putting it in an Island is effectively the most "symmetric" test when comparing to Remix/NextJS.

**Comment by iainsimmons** [comment]
Yeah I guess the only difference is the extra HTML code for hydration (script tags and serialised data, if any).

**Comment by jherr** [comment]
Added. Very fast. 11538 req/s with 4 ms latency.

**Comment by iainsimmons** [comment]
Oooh spicy! 😁
